export const SEARCH_MOVIES_STARTED = 'SEARCH_MOVIES_STARTED';

export const SEARCH_MOVIES_SUCCESS = 'SEARCH_MOVIES_SUCCESS';

export const SEARCH_MOVIES_FAIL = 'SEARCH_MOVIES_FAIL';

export const CLEAR_SEARCH_RESULTS = 'CLEAR_SEARCH_RESULTS';
