export const GET_MOVIE_INFO_STARTED = 'GET_MOVIE_INFO_STARTED';

export const GET_MOVIE_INFO_SUCCESS = 'GET_MOVIE_INFO_SUCCESS';

export const GET_MOVIE_INFO_FAIL = 'GET_MOVIE_INFO_FAIL';

export const CLEAR_MOVIE_INFO = 'CLEAR_MOVIE_INFO';
